apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mce-okd-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jbweber/okd-config'  # Update this
    targetRevision: main
    path: apps/mce/overlays/okd-1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stolostron-engine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
