apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespace: multicluster-engine
  availabilityConfig: Basic  # Use "High" for HA in production
